version: '3.4'

services:
  qpafinalproject:
    image: qpafinalproject
    build:
      context: ./project
      dockerfile: ./Dockerfile
    volumes:
        - script_data:/app/data/output_data
    networks:
        - mynetwork
    depends_on:
        - db
    links:
        - db:db

  db:
    container_name: postgres1
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    networks:
      - mynetwork
volumes:
  postgres_data:
  script_data:


networks:
      mynetwork:
          driver: bridge