import os, sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)

import unittest
from os.path import exists

'''
This is a script for testing the functions of script.py built in Part 1 and Part3 of qpa
final project. Testing is done using unittest module.
The file is located in the same folder as script.py, to avoid Import Errors and appending sys.path.  
'''


class testGcPlot(unittest.TestCase):

    def test_gc_plot_exists(self):
        '''Testing if GC-content plot was generated by gc_content_subseq function'''
        path = "output_data/gc_dist.png"
        gc_content_subseq("ATTTGGCTACTAACAATCTA", 3)
        self.assertTrue(exists(path), "GC-content plot was not generated")


if __name__ == '__main__':
    unittest.main()
